[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "konanai"
authors = [{name = "Joseph Konan", email = "konan@konanai.com"}]
dynamic = ["version", "description"]
